import Cards from '@/components/Cards/Cards'
import StatCards from '@/components/Cards/StatCards'
import Head from 'next/head'
import Image from 'next/image'

export default function Home() {


    const config = {
        botdavet: "https://google.com"
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="container mx-auto">
                <div className='flex flex-col justify-center items-center h-[500px] gap-10'>
                    <div className=''>

                        <h1 className='md:text-5xl text-3xl font-bold text-white w-[450px] md:w-full'><span className='text-blue-600'>PlusBot</span> ile sunucunuz daha iyi</h1>
                    </div>
                    <div className='flex gap-5'>
                        <a href={config.botdavet} className='bg-sky-600/20 font-semibold hover:bg-sky-600/30 px-8 py-3 rounded-lg text-blue-600 hover:-translate-y-3 duration-300'>Sunucuna Ekle</a>
                        <a href={config.botdavet} className='bg-blue-600 px-8 rounded-lg text-white hover:bg-blue-900 flex justify-center items-center hover:translate-y-3 duration-300'>Giriş Yap</a>
                    </div>
                </div>

                <div className=''>
                    <div className='md:flex flex flex-wrap text-center justify-between items-center'>
                        <div className="w-[600px] h-[300px] relative">
                            <Image alt='' src={'/images/pb-bg.png'} fill className='rounded-xl' />
                        </div>
                        <div className=''>
                            <h1 className='text-5xl font-bold'>
                                <span className='text-blue-600'>Plus</span>
                                <span className='text-white'>Bot</span>
                            </h1>
                            <p className='md:w-[450px] w-[300px] text-white font-medium text-sm'>Yetkili ve koruma Komutları ile sunucunuzu daha güvenli hale getirin</p>
                        </div>
                    </div>
                </div>




                <div className="mt-20">
                    <Cards />
                </div>


                <div className='md:flex flex-wrap justify-center  md:justify-between items-center my-10'>
                    <div className=' flex flex-col  gap-5 my-10'>
                        <h1 className='text-4xl font-bold'>
                            <span className='text-blue-600'>Plus</span>
                            <span className='text-white'>Bot</span>
                        </h1>
                        <div className="flex justify-start flex-wrap gap-10">
                            <StatCards />
                        </div>
                    </div>
                    <div>
                        <p className='w-[330px] text-gray-400 font-semibold'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio voluptatum tenetur nulla, dolorum vero commodi unde eum, incidunt voluptatibus optio distinctio quibusdam amet, temporibus assumenda animi magnam aperiam adipisci atque?</p>
                    </div>
                </div>

            </div>

        </>
    )
}
